[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower, PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(List<GitHubRepository>))]
[JsonSerializable(typeof(GitHubWorkflows))]
[JsonSerializable(typeof(GitHubRuns))]
[JsonSerializable(typeof(GitHubJobs))]
[JsonSerializable(typeof(GitHubArtifacts))]
[JsonSerializable(typeof(GitHubUser))]
[JsonSerializable(typeof(GitHubPullRequest))]
[JsonSerializable(typeof(List<GitHubPullRequest>))]
[JsonSerializable(typeof(GitHubBranch))]
[JsonSerializable(typeof(List<GitHubRef>))]
partial class GitHubContext : JsonSerializerContext;
