<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Argon" Version="0.37.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="IconifyBundle.Lucide" Version="1.0.2" />
    <PackageVersion Include="IconifyBundle.SimpleIcons" Version="1.0.2" />
    <PackageVersion Include="MarkdownSnippets.MsBuild" Version="28.4.2" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageVersion Include="ModelContextProtocol" Version="2.2.0" />
    <PackageVersion Include="Polyfill" Version="11.4.0" />
    <PackageVersion Include="ProjectDefaults" Version="1.0.181" />
    <PackageVersion Include="Serilog" Version="4.4.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="SimpleInfoName" Version="3.2.0" />
    <PackageVersion Include="SkiaSharp" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="4.152.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="4.152.1" />
    <PackageVersion Include="Svg.Skia" Version="5.2.3" />
    <PackageVersion Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <PackageVersion Include="Tmds.DBus.Protocol" Version="0.95.1" />
    <PackageVersion Include="TUnit" Version="1.68.17" />
    <PackageVersion Include="Verify" Version="33.1.1" />
    <PackageVersion Include="Verify.TUnit" Version="33.1.1" />
    <PackageVersion Include="Verify.WinForms" Version="6.0.0" />
  </ItemGroup>
</Project>
